abifajri/urls.py
from django.urls import include, path
from .views import index, more

urlpatterns = [
    path('', index, name='index'),
    path('more/', more, name='more'),
]

myschedule/urls.py
from django.urls import include, path
from .views import myschedule, save_activity, delete_activity

app_name = 'myschedule'

urlpatterns = [
    path('', myschedule, name='index'),
    path('save_activity', save_activity, name='save_activity'),
    path('delete_activity/<int:delete_id>',delete_activity,name='delete_activity'),
]

workspace/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('abifajri.urls')),
    path('myschedule/', include('myschedule.urls', namespace='myschedule')),
]

abifajri/models.py
from django.db import models

# Create your models here.

myschedule/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

# Create your models here.
class Schedule(models.Model):
    activity = models.CharField(max_length=20)
    place = models.CharField(max_length=20)
    category = models.CharField(max_length=20)
    date_time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.activity

myschedule/forms.py
from django import forms
from .models import Schedule

class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = '__all__'
        widgets = {
            'activity': forms.TextInput(attrs={'size': 20}),
            'place': forms.TextInput(attrs={'size': 20}),
            'category': forms.TextInput(attrs={'size': 20}),
        }

abifajri/views.py
from django.shortcuts import render, redirect

name = 'Abi Fajri Abdillah'

def index(request):
    response = {'name' : name}
    return render(request,'index.html',response)

def more(request):
    response = {'name' : name}
    return render(request,'more.html',response)

myschedule/views.py
from django.shortcuts import render, redirect

from .models import Schedule
from .forms import ScheduleForm

# Create your views here.
def myschedule(request):
    schedules = Schedule.objects.all().values()

    response = {
        'form': ScheduleForm,
        'schedules' : schedules
    }

    return render(request, 'myschedule.html', response)


def save_activity(request):
    form = ScheduleForm(request.POST or None)
    if (request.method == 'POST' and form.is_valid()):
        form.save()
        return redirect('myschedule:index')
    
    else:
        return redirect('myschedule:index')    

def delete_activity(request, delete_id):
   Schedule.objects.filter(id=delete_id).delete()
   return redirect('myschedule:index')

abifajri/templates/contents/navbar.html
{% load static %}
<nav class="navbar navbar-expand-sm justify-content-end navbar-light">
    <div class="container">
        <a class="navbar-brand" href="..">
            abi<span style="color: #156588">fajri</span>
            <hr class="hr-navbrand">
        </a>
        <ul class="navbar-nav">
            <li class="nav-item">
            <a class="nav-link" href="#">projects<hr class="hr-navitem"></a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="#about">about<hr class="hr-navitem"></a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="#contact">contact<hr class="hr-navitem"></a>
            </li>
        </ul>
    </div>
</nav>

abifajri/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    
    {% include 'contents/style.html' %}

    <title>abifajri</title>
</head>

<body id="top">

    <nav class="navbar navbar-expand-sm justify-content-end navbar-light">
        <div class="container">
            <a class="navbar-brand" href="/">
                abi<span style="color: #156588">fajri</span>
                <hr class="hr-navbrand">
            </a>
            <ul class="navbar-nav">
                <li class="nav-item">
                <a class="nav-link" href="#">projects<hr class="hr-navitem"></a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="#about">about<hr class="hr-navitem"></a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="#contact">contact<hr class="hr-navitem"></a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col" id="logo-sp">
                <img class="sp" src="{% static 'img/logo-sp.jpg' %}">
            </div>
        
            <div class="col" id="intro">
                <div class="my-name">
                    abi fajri <a style="color: #156588">abdillah</a>
                    <div class="game-designer">future game designer.<hr class="hr-intro1"></div>
                    <hr class="hr-intro2">
                </div>
            </div>
        </div>
    </div>
    
    <div class="container">
        <hr class="hr-long">
    </div>

    <div class="container">
        <div class="row">
            <div class="col-sm-5" id="about">
                <img class="my-pict" src="{% static 'img/my-pict.jpg' %}">
                <br><br>
                <p>
                    Hi <a style="color: #156588">there!</a>
                    <br>
                    I love to play <a style="color: #156588">video games</a>,
                    <br>
                    watch <a style="color: #156588">movies</a>, and <a style="color: #156588">schleep</a>!
                </p>
            </div>

            <div class="hide-mobile col-sm-1">
                <div class="v-line1"></div>
            </div>

            <div class="hide-mobile col-sm-1">
                <div class="v-line2"></div>
            </div>
        
            <div class="show-mobile col-sm-2">
                <hr class="hr-long">
            </div>

            <div class="col-sm-5" id="contact">
                let's be <a style="color: #156588">friends</a>!
                <ul class="contact">
                    <a href="http://facebook.com/abi.f.abdillah"><img class="img-contact" src="{% static 'img/fb.png' %}" style="width:60px;height:60px"></a>
                    <a href="https://www.linkedin.com/in/abi-fajri-abdillah-989088176/"><img class="img-contact" src="{% static 'img/in.png' %}"></a>
                    <a href="http://instagram.com/abifajri_"><img class="img-contact" src="{% static 'img/ig.png' %}"></a>
                    <a href="mailto:a.fajri303@gmail.com"><img class="img-contact" src="{% static 'img/email.png' %}"></a>
                </ul>
                <div class="bio">know me <a href="more" style="color: #156588">more</a>.</div>
            </div>
        </div>
    </div>

    <div class="container">
        <hr class="hr-long">
    </div>
        
    <script src="{% static 'js/jquery.min.js' %}"></script> 
    <script src="{% static 'js/popper.min.js' %}"></script> 
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>

<footer>
    <p> Abi Fajri Abdillah &#169 2019 </p>
</footer>

</html>

abifajri/templates/more.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    {% include 'contents/style.html' %}
    
    <title>more</title>
</head>

<body id="top">

    <nav class="navbar navbar-expand-sm justify-content-end navbar-light">
       <div class="container">
            <a class="navbar-brand" href="/">
                abi<span style="color: #156588">fajri</span>
                <hr class="hr-navbrand">
            </a>
            <ul class="navbar-nav">
                <li class="nav-item">
                <a class="nav-link" href="#">projects<hr class="hr-navitem"></a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="/#about">about<hr class="hr-navitem"></a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="/#contact">contact<hr class="hr-navitem"></a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-sm-5" id="educations">
                <h2 style="font-weight:600;font-size:28px">
                    Edu<span style="color:#156588">cations</span>:
                </h2>
                <p>
                    - Computer Science Undergraduate Student <br>
                    <a href="https://www.ui.ac.id/en/" style="color:#156588">@University of Indonesia</a> | 2018 - Present
                </p>
                <br>
                <h2 style="font-weight:600;font-size:28px">
                    Skill<span style="color:#156588">s</span>:
                </h2>
                <p class="skills">
                    - Python <br>
                    - Java <br>
                    - Unity3D
                </p>
            </div>
        
            <div class="hide-mobile col-sm-1">
                <div class="v-line1"></div>
            </div>

            <div class="hide-mobile col-sm-1">
                <div class="v-line2"></div>
            </div>
        
            <div class="show-mobile col-sm-2">
                <hr class="hr-long">
            </div>
        
            <div class="col-sm-5" id="contact">
                let's be <a style="color: #156588">friends!</a>
                <ul class="contact">
                        <a href="http://facebook.com/abi.f.abdillah"><img class="img-contact" src="{% static 'img/fb.png' %}" style="width:60px;height:60px"></a>
                        <a href="https://www.linkedin.com/in/abi-fajri-abdillah-989088176/"><img class="img-contact" src="{% static 'img/in.png' %}"></a>
                        <a href="http://instagram.com/abifajri_"><img class="img-contact" src="{% static 'img/ig.png' %}"></a>
                        <a href="mailto:a.fajri303@gmail.com"><img class="img-contact" src="{% static 'img/email.png' %}"></a>
                </ul>
            </div>
        </div>
    </div>
    
    <div class="container">
        <hr class="hr-long">
    </div>
        
    <script src="{% static 'js/jquery.min.js' %}"></script> 
    <script src="{% static 'js/popper.min.js' %}"></script> 
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>

<footer>
    <p> Abi Fajri Abdillah &#169 2019 </p>
</footer>

</html>

myschedule/templates/contents/style.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700&display=swap" rel="stylesheet">

<!-- <link rel="icon" type="image/png" href=""> -->

myschedule/templates/myschedule.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    
    {% include 'contents/style.html' %}

    <title>myschedule</title>
</head>

<body id="top">

    <nav class="navbar navbar-expand-sm justify-content-end navbar-light">
        <div class="container">
            <a class="navbar-brand" href="/">
                abi<span style="color: #156588">fajri</span>
                <hr class="hr-navbrand">
            </a>
            <ul class="navbar-nav">
                <li class="nav-item">
                <a class="nav-link" href="#">projects<hr class="hr-navitem"></a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="/#about">about<hr class="hr-navitem"></a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="/#contact">contact<hr class="hr-navitem"></a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <h3 style="margin-bottom: 10px">Add your activity <a style="color: #156588">here</a>!</h3>
        <form action="save_activity" method="POST">
            {% csrf_token %}
            <table style="margin:auto">
            {{ form.as_table }}
            </table>
            <button type="submit" class="btn btn-primary" style="margin-top: 10px">Submit</button>
        </form>	
    </div>

    <br>

    <div class="container">
        <h1 class="display-5" style="text-align : center; margin-top: 15px;">Schedules</h1>
        <table class="table">
           <thead>
              <tr>
                 <th scope="col">#</th>
                 <th scope="col">Activity</th>
                 <th scope="col">Place</th>
                 <th scope="col">Category</th>
                 <th scope="col">Date/Time</th>
                 <th scope="col">Delete</th>
              </tr>
           </thead>
           <tbody>
              {% for schedule in schedules %}
              <tr>
                 <th scope="row">{{forloop.counter}}</th>
                 <td>{{schedule.activity}}</td>
                 <td>{{schedule.place}}</td>
                 <td>{{schedule.category}}</td>
                 <td>{{schedule.date_time}}</td>
                 <td><a href="{% url 'myschedule:delete_activity' schedule.id %}" class="btn-outline btn-danger">Delete</a></td>
              {% endfor %}
              </tr>
           </tbody>
        </table>
     </div>
        
    <script src="{% static 'js/jquery.min.js' %}"></script> 
    <script src="{% static 'js/popper.min.js' %}"></script> 
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>

</html>